### ISSUE TITLE
GitLens connect to GitHub error

### ISSUE THREAD

**Issue by Dulanic** [gitkraken/vscode-gitlens#1228]
Error:
Prompted with:
![image](https://user-images.githubusercontent.com/2948206/100762572-beeb7380-33b9-11eb-98a0-9a07660e59ff.png)
Result:
![image](https://user-images.githubusercontent.com/2948206/100762614-cd398f80-33b9-11eb-8362-01a4ef223eee.png)

- GitLens Version:
- Git Version: `run git --version`

git version 2.17.1

- VSCode Version: `run code --version`

code-server: v3.7.3
 VS Code: v1.51.1
Commit: 93fb76e4a71b1959ec2a23481ba2611200d714b2
Date: 2020-11-24T18:31:53Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.67 Safari/537.36 Edg/87.0.664.47

- OS Version:
Ubuntu 20.10
Using docker version of vscode 

https://github.com/linuxserver/docker-mods/tree/code-server-docker

Steps to Reproduce:

1. Install docker vs-code server.
```
version: "3.4"
services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: vscode
    restart: unless-stopped
    env_file:
      - ./envs/main.env
      - ./envs/vscode.env
    volumes:
      - ./vscode/config:/config # Contains all relevant configuration files.
      - /opt/python_scripts:/opt/python_scripts #python_scripts
      - /mnt/ssd/docker:/mnt/ssd/docker
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8443:8443/tcp # Web UI  
```
env files settings...

```
PUID=1000
PGID=1000
TZ=America/Chicago
PROXY_DOMAIN=code.dulanic.com
DOCKER_MODS=linuxserver/mods:code-server-docker|code-server-python3
PASSWORD=redacted
```

2. Setup SSH key etc...
3. Install gitlens
4. Follow prompt and receive error.
