### ISSUE TITLE
Git blame not working in my (a?) devcontainer

### ISSUE THREAD

**Issue by blieusong** [gitkraken/vscode-gitlens#2034]
- GitLens Version: v12.0.7
- Git Version: 2.25.1

- VSCode Version: 1.68.0, 4af164ea3a06f701fe3e89a2bcbb421d2026b68f, x64
- OS Version: Linux gbprod-sybase 5.4.0-1083-azure #87~18.04.1-Ubuntu SMP Fri Jun 3 13:19:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Check that gitlens git line blame works in a project
2. Create devcontainer setup with extension **eamodio.gitlens**
3. Open the project in devcontainer
4. Git line blame doesn't work

My devcontainer setup : 
```json
{
	"name": "gbprod/picone",
	"dockerComposeFile": "docker-compose.yml",
	"service": "gbprod-sybase",
	"runServices": [
		"gbprod-sybase"
	],
	"workspaceFolder": "/workspace",
	"extensions": [
		"ms-vscode.cpptools",
		"mhutchie.git-graph",
		"eamodio.gitlens",
		"foxundermoon.shell-format",
		"Gruntfuggly.todo-tree",
		"cschlosser.doxdocgen",
		"GitLab.gitlab-workflow",
		"mechatroner.rainbow-csv"
	],
	"shutdownAction": "stopCompose",
	"postCreateCommand": "update_libs.sh",
	"postStartCommand": "start_ssh_tunnels.sh DEV"
}
```
part of the `docker-compose.yml` file I use

```yaml
version: "3.7"

services:
  gbprod-sybase:
    image: ${DOCKER_REGISTRY}/sybase
    hostname: gbprod-sybase
    working_dir: /workspace
    environment:
      - GBPROD_RELEASE=${GBPROD_RELEASE}
    volumes:
      - ..:/workspace # workspace
      - ~/projects/document:/workspace/document
      - spg_sybase:/opt/gbprod/SPG 
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - bashhistory:/commandhistory
    networks:
      gbprod-bridge:
    expose:
      - "44444"
    dns_search:
      - xxxx
    # option ci-dessous nécessaire pour le gdb distant.
    # ne PAS faire ça sur un conteneur de prod.
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    tty: true

  mssql-server:
    image: mcr.microsoft.com/mssql/server:latest
    hostname: mssql-server
    environment:
      - MSSQL_SA_PASSWORD=xxxx
      - MSSQL_LCID=1033
      - MSSQL_COLLATION=Latin1_General_100_BIN2
      - MSSQL_MEMORY_LIMIT_MB=4096
      - MSSQL_BACKUP_DIR=/var/opt/mssql/data/
      - MSSQL_DATA_DIR=/var/opt/mssql/data/
      - MSSQL_LOG_DIR=/var/opt/mssql/data/
      - MSSQL_DUMP_DIR=/var/opt/mssql/data/
      - ACCEPT_EULA=y
      - MSSQL_ENABLE_AGENT=false
    volumes:
      - mssql-data:/var/opt/mssql/data
    user: "root:root"
    networks:
      gbprod-bridge:
    tty: true
  
  ase-server:
    image: ${DOCKER_REGISTRY}/ase-server:15.7
    hostname: ase-server
    working_dir: /home/sybase
    volumes:
      - ase-data:/data
    networks:
      gbprod-bridge:
    tty: true
    entrypoint: "/home/sybase/bin/entrypoint.sh"

networks:
  gbprod-bridge:
    ipam:
      driver: default

volumes:
  spg_freetds:
  spg_sybase:
  bashhistory:
  mssql-data:
  ase-data:
```
