### ISSUE TITLE
Add vllm support

### ISSUE THREAD

**Issue by MattTheCuber** [gitkraken/vscode-gitlens#4304]
### Description

Relates to #3311

It would be great to be able to specify my AI endpoint for a VLLM-hosted model.

[Continue](https://www.continue.dev/) has a really good system for local AI configuration if you are looking for some implementation ideas. 

Example:

```yaml
models:
  - name: Qwen
    provider: openai
    apiType: openai
    model: Qwen/Qwen2.5-Coder-32B-Instruct-GPTQ-Int8
    # apiBase": http://10.10.155.14:7007/v1
    apiBase: http://10.10.10.178:7007/v1
    roles:
      - chat
      - edit
      - apply
      - autocomplete
```
